# Site-wide settings
# ------------------

title: Your awesome title

author:
  name: GitHub User
  email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
skin: litera  # See themes at https://bootswatch.com/
date_format: "%b %d, %Y"

# Build settings
# --------------

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
